/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import DAO.MetodosLivros;
import DAO.AdicionarUsuario;
import DAO.Solicitacoes;
import DAO.Sugestao;
import classes.Livro;
import classes.Solicitacao;
import classes.Usuario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Menu extends javax.swing.JFrame {
        Usuario usuarioLogado = new Usuario();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        preencheTabelaLivros("");
        InicializaAluno(false); //Deixa apenas o login visivel
        

    }
    private void InicializaAdmin(){
            TextoBarraCima.setVisible(true);
            TextoBarraCima.setText("Boas Vindas " + usuarioLogado.getNome());
            MenuBarAluno.setVisible(false);
            MenuBarAdmin.setVisible(true);
            PainelLogin.setVisible(false);
            PainelAddObra.setVisible(true);
    }
    private void InicializaAluno(boolean t) {
            TextoBarraCima.setVisible(t);
            TextoBarraCima.setText("Boas Vindas " + usuarioLogado.getNome());
            BotaoAcervo.setVisible(t);
            BotaoSolicitacoes.setVisible(t);
            jButton1.setVisible(t);
            BotaoSugerir.setVisible(t);                  
            PainelBusca.setVisible(t);
            PainelAddObra.setVisible(false);
            MenuBarAdmin.setVisible(false);
            PainelSugestoes.setVisible(false);
            PainelSolicitacoes.setVisible(false);
            PainelRegistro.setVisible(false);
            PainelLogin.setVisible(!t);                         //Deixa apenas o painel de login visivel ao iniciar o programa
       
    }
    
    private void preencheTabelaLivros(String text) { //Método para popular a tabela livros com os dados
    
    MetodosLivros livroDAO = new MetodosLivros();
    List<Livro> listaLivros = livroDAO.buscaLivro(text);

    DefaultTableModel tabelaLivros = (DefaultTableModel) TabelaLivros.getModel();
    tabelaLivros.setNumRows(0);

    if (listaLivros != null && !listaLivros.isEmpty()) {
        for (Livro livro : listaLivros) {
            System.out.println("Listando Livros");
            Object[] obj = new Object[]{
                    livro.getId(),
                    livro.getTitulo(),
                    livro.getAutor(),
                    livro.getVolume(),
            };
            tabelaLivros.addRow(obj);
        }
    } else {
        System.out.println("Nenhum livro encontrado");
    }
}
    
    private void preencheTabelaSolicitacoes(Usuario user) { //Método para popular a tabela solicitacoes com os dados
    
    Solicitacoes soli = new Solicitacoes();
    int userID = AdicionarUsuario.getIdUsuario(user.getNome());
    List<Solicitacao> listaSoli =soli.BuscaSolicitacoes(userID);

    DefaultTableModel tabelaSoli = (DefaultTableModel) TabelaSoli.getModel();
    tabelaSoli.setNumRows(0);

    if (listaSoli != null && !listaSoli.isEmpty()) {
        for (Solicitacao sol : listaSoli) {
            System.out.println("Listando Solicitaçoes: ");
            Object[] obj = new Object[]{
                sol.getNome(),
                sol.getISBN(),
                sol.getAluno_id(),
            };
            System.out.println("Adicionado: "+sol.getNome());
        tabelaSoli.addRow(obj);}
        }else {
        System.out.println("Nenhuma solicitação encontrada: ");
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraCima = new javax.swing.JPanel();
        TextoBarraCima = new javax.swing.JLabel();
        MenuBarAdmin = new javax.swing.JPanel();
        AdicionarBibliotecario = new javax.swing.JButton();
        AdicionarObra = new javax.swing.JButton();
        Exemplares = new javax.swing.JButton();
        MenuBarAluno = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        BotaoAcervo = new javax.swing.JButton();
        BotaoSolicitacoes = new javax.swing.JButton();
        BotaoSugerir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        PainelAddObra = new javax.swing.JPanel();
        PainelBusca = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaLivros = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        SearchBar = new java.awt.TextField();
        Solicitar = new java.awt.Button();
        PainelSugestoes = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        submeteSugestao = new javax.swing.JButton();
        sugestaoVolume = new javax.swing.JTextField();
        sugestaoAutor = new javax.swing.JTextField();
        sugestaoNome = new javax.swing.JTextField();
        PainelSolicitacoes = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        ScrollSoli = new javax.swing.JScrollPane();
        TabelaSoli = new javax.swing.JTable();
        PainelLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeLoginBox = new javax.swing.JTextField();
        Entrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Registrar = new javax.swing.JButton();
        senhaLoginBox = new javax.swing.JPasswordField();
        PainelRegistro = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        confSenhaBox = new javax.swing.JTextField();
        EnviarRegistro = new javax.swing.JButton();
        BotaoLogin = new javax.swing.JButton();
        nomeBox = new javax.swing.JTextField();
        emailBox = new javax.swing.JTextField();
        senhaBox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(187, 187, 187));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraCima.setBackground(new java.awt.Color(188, 141, 97));

        TextoBarraCima.setBackground(new java.awt.Color(0, 0, 0));
        TextoBarraCima.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoBarraCima.setForeground(new java.awt.Color(0, 0, 0));
        TextoBarraCima.setText("Boas Vindas " + usuarioLogado.getNome());

        javax.swing.GroupLayout BarraCimaLayout = new javax.swing.GroupLayout(BarraCima);
        BarraCima.setLayout(BarraCimaLayout);
        BarraCimaLayout.setHorizontalGroup(
            BarraCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCimaLayout.createSequentialGroup()
                .addContainerGap(507, Short.MAX_VALUE)
                .addComponent(TextoBarraCima, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(303, 303, 303))
        );
        BarraCimaLayout.setVerticalGroup(
            BarraCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextoBarraCima, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(BarraCima, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 30));

        MenuBarAdmin.setBackground(new java.awt.Color(231, 220, 192));
        MenuBarAdmin.setForeground(new java.awt.Color(231, 220, 192));

        AdicionarBibliotecario.setText("Bibliotecários");
        AdicionarBibliotecario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarBibliotecarioActionPerformed(evt);
            }
        });

        AdicionarObra.setText("Adicionar Obra");
        AdicionarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarObraActionPerformed(evt);
            }
        });

        Exemplares.setText("Exemplares");
        Exemplares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExemplaresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuBarAdminLayout = new javax.swing.GroupLayout(MenuBarAdmin);
        MenuBarAdmin.setLayout(MenuBarAdminLayout);
        MenuBarAdminLayout.setHorizontalGroup(
            MenuBarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuBarAdminLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(MenuBarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AdicionarObra, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exemplares, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdicionarBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        MenuBarAdminLayout.setVerticalGroup(
            MenuBarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuBarAdminLayout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(AdicionarObra, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AdicionarBibliotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Exemplares, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
        );

        getContentPane().add(MenuBarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 550));

        MenuBarAluno.setBackground(new java.awt.Color(231, 220, 192));
        MenuBarAluno.setForeground(new java.awt.Color(231, 187, 187));
        MenuBarAluno.setToolTipText("");
        MenuBarAluno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        MenuBarAluno.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 342, 135, 61));

        BotaoAcervo.setText("Acervo");
        BotaoAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAcervoActionPerformed(evt);
            }
        });
        MenuBarAluno.add(BotaoAcervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 123, 135, 61));

        BotaoSolicitacoes.setText("Solicitações");
        BotaoSolicitacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSolicitacoesActionPerformed(evt);
            }
        });
        MenuBarAluno.add(BotaoSolicitacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 196, 135, 61));

        BotaoSugerir.setText("Sugerir uma Obra");
        BotaoSugerir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSugerirActionPerformed(evt);
            }
        });
        MenuBarAluno.add(BotaoSugerir, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 269, 135, 61));

        getContentPane().add(MenuBarAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 210, 550));

        jPanel2.setBackground(new java.awt.Color(187, 187, 187));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelAddObra.setBackground(new java.awt.Color(187, 187, 187));
        PainelAddObra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(PainelAddObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 550));

        PainelBusca.setBackground(new java.awt.Color(187, 187, 187));
        PainelBusca.setAutoscrolls(true);
        PainelBusca.setPreferredSize(new java.awt.Dimension(534, 343));
        PainelBusca.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabelaLivros.setBackground(new java.awt.Color(204, 204, 204));
        TabelaLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Título", "Autor", "Volume"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaLivros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TabelaLivros.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jScrollPane1.setViewportView(TabelaLivros);
        if (TabelaLivros.getColumnModel().getColumnCount() > 0) {
            TabelaLivros.getColumnModel().getColumn(0).setResizable(false);
            TabelaLivros.getColumnModel().getColumn(1).setResizable(false);
            TabelaLivros.getColumnModel().getColumn(2).setResizable(false);
            TabelaLivros.getColumnModel().getColumn(3).setResizable(false);
        }

        PainelBusca.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 710, 430));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Busque uma Obra!");
        PainelBusca.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 300, -1));

        SearchBar.setBackground(new java.awt.Color(204, 204, 204));
        SearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBarActionPerformed(evt);
            }
        });
        SearchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchBarKeyReleased(evt);
            }
        });
        PainelBusca.add(SearchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 630, -1));

        Solicitar.setBackground(new java.awt.Color(204, 204, 204));
        Solicitar.setLabel("Solicitar");
        Solicitar.setMaximumSize(new java.awt.Dimension(75, 25));
        Solicitar.setMinimumSize(new java.awt.Dimension(75, 25));
        Solicitar.setName(""); // NOI18N
        Solicitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SolicitarMouseClicked(evt);
            }
        });
        Solicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolicitarActionPerformed(evt);
            }
        });
        PainelBusca.add(Solicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, -1, -1));

        jPanel2.add(PainelBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 550));

        PainelSugestoes.setBackground(new java.awt.Color(187, 187, 187));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Sugira uma aquisição!");
        jLabel10.setToolTipText("");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Nome do Livro:");

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Autor:");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Volume:");

        submeteSugestao.setText("Submeter");
        submeteSugestao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submeteSugestaoActionPerformed(evt);
            }
        });

        sugestaoVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sugestaoVolumeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelSugestoesLayout = new javax.swing.GroupLayout(PainelSugestoes);
        PainelSugestoes.setLayout(PainelSugestoesLayout);
        PainelSugestoesLayout.setHorizontalGroup(
            PainelSugestoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelSugestoesLayout.createSequentialGroup()
                .addGroup(PainelSugestoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelSugestoesLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(PainelSugestoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelSugestoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sugestaoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sugestaoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sugestaoVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PainelSugestoesLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel10))
                    .addGroup(PainelSugestoesLayout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(submeteSugestao, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        PainelSugestoesLayout.setVerticalGroup(
            PainelSugestoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelSugestoesLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel10)
                .addGap(54, 54, 54)
                .addGroup(PainelSugestoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(sugestaoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelSugestoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(sugestaoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelSugestoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sugestaoVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelSugestoesLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(30, 30, 30)
                .addComponent(submeteSugestao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );

        jPanel2.add(PainelSugestoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 570));

        PainelSolicitacoes.setBackground(new java.awt.Color(187, 187, 187));
        PainelSolicitacoes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel9.setText("Minhas Solicitações!");
        PainelSolicitacoes.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 353, -1));

        TabelaSoli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Obra", "ISBN", "Recebimento", "Devolução"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollSoli.setViewportView(TabelaSoli);
        if (TabelaSoli.getColumnModel().getColumnCount() > 0) {
            TabelaSoli.getColumnModel().getColumn(0).setResizable(false);
            TabelaSoli.getColumnModel().getColumn(1).setResizable(false);
            TabelaSoli.getColumnModel().getColumn(2).setResizable(false);
            TabelaSoli.getColumnModel().getColumn(3).setResizable(false);
        }

        PainelSolicitacoes.add(ScrollSoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 710, -1));

        jPanel2.add(PainelSolicitacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 550));

        PainelLogin.setBackground(new java.awt.Color(187, 187, 187));
        PainelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nome de Usuário:");
        PainelLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Senha:");
        PainelLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));
        PainelLogin.add(nomeLoginBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 200, -1));

        Entrar.setText("Entrar");
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });
        PainelLogin.add(Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 90, 60));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Faça seu Login!");
        PainelLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, 50));

        Registrar.setText("Registrar");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });
        PainelLogin.add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 90, 60));
        PainelLogin.add(senhaLoginBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 200, -1));

        jPanel2.add(PainelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 550));

        PainelRegistro.setBackground(new java.awt.Color(187, 187, 187));
        PainelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("E-mail:");
        PainelRegistro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 208, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nome:");
        PainelRegistro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 180, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Senha:");
        PainelRegistro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 236, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Confirmar senha:");
        PainelRegistro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));
        PainelRegistro.add(confSenhaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 270, -1));

        EnviarRegistro.setText("Enviar");
        EnviarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarRegistroActionPerformed(evt);
            }
        });
        PainelRegistro.add(EnviarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));

        BotaoLogin.setText("Login");
        BotaoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLoginActionPerformed(evt);
            }
        });
        PainelRegistro.add(BotaoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));
        PainelRegistro.add(nomeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 177, 270, -1));
        PainelRegistro.add(emailBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 205, 270, -1));
        PainelRegistro.add(senhaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 233, 270, -1));

        jPanel2.add(PainelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -2, 930, 560));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 28, 923, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
        String nomeEnviar = nomeLoginBox.getText();
        String senhaEnviar = senhaLoginBox.getText();
        System.out.println("Antes autenticação "+nomeEnviar);
        if (AdicionarUsuario.autenticar(nomeEnviar, senhaEnviar)){
            System.out.println("autenticou");
            usuarioLogado.setNome(nomeEnviar);
            usuarioLogado.setEmail(AdicionarUsuario.getEmailUsuario(nomeEnviar));
            usuarioLogado.setAdmin(AdicionarUsuario.getAdminUsuario(nomeEnviar));            
            System.out.println(usuarioLogado.getNome() + " "+ usuarioLogado.getEmail() + "" + usuarioLogado.getAdmin());
            if (usuarioLogado.getAdmin()){
                System.out.println("chegou admin");
                InicializaAdmin();
            }else{
                System.out.println("chegou aluno");
                InicializaAluno(true);             
            }
        }else{
            JOptionPane.showMessageDialog(this, "Usuário ou senha Incorretos", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_EntrarActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        // TODO add your handling code here:
       PainelRegistro.setVisible(true);
       PainelLogin.setVisible(false);
    }//GEN-LAST:event_RegistrarActionPerformed

    private void EnviarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarRegistroActionPerformed
        // TODO add your handling code here:
     
         String nomeEnviar = nomeBox.getText().trim();
         String emailEnviar = emailBox.getText().trim();
         String senhaEnviar = senhaBox.getText().trim();
         String senhaConf = confSenhaBox.getText().trim(); // pegar os dados dos campos
         System.out.println(nomeEnviar); // depuração

// Verifica se algum dos campos está vazio
        if (nomeEnviar.isEmpty() || emailEnviar.isEmpty() || senhaEnviar.isEmpty() || senhaConf.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            if (!AdicionarUsuario.usuarioExiste(nomeEnviar, emailEnviar)) { // se não houver usuário correspondente, prossegue para a criação
            System.out.println("Pronto para adicionar usuário"); // depuração

            if (senhaEnviar.length() < 5) { // verifica se a senha tem no mínimo 5 dígitos
                JOptionPane.showMessageDialog(this, "A senha deve ter no mínimo 5 dígitos.", "Erro", JOptionPane.ERROR_MESSAGE);
            } else if (senhaEnviar.equals(senhaConf)) { // checa se as senhas correspondem
                AdicionarUsuario.addUser(nomeEnviar, senhaEnviar, emailEnviar, false);
                JOptionPane.showMessageDialog(this, "Usuário adicionado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                PainelRegistro.setVisible(false);
                PainelLogin.setVisible(true); // abre o painel de login após o registro concluído
                PainelBusca.setVisible(false);
            } else { // manda uma mensagem de erro se as senhas não corresponderem
                JOptionPane.showMessageDialog(this, "Falha: as senhas não correspondem", "Erro", JOptionPane.ERROR_MESSAGE);
                System.out.println("Falha: as senhas não correspondem");
                System.out.println("Senha enviada: " + senhaEnviar);
                System.out.println("Senha de confirmação: " + senhaConf);
            }
            }  else { // se houver um usuário já com o nome ou e-mail retorna um erro
                JOptionPane.showMessageDialog(this, "Nome de Usuário ou e-mail já em uso", "Erro", JOptionPane.ERROR_MESSAGE);
    }
}

    }//GEN-LAST:event_EnviarRegistroActionPerformed

    private void BotaoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLoginActionPerformed
             PainelRegistro.setVisible(false);
             PainelLogin.setVisible(true);
             PainelRegistro.repaint();
             PainelRegistro.revalidate();             //deixa somente o panel login visível
             PainelLogin.repaint();
             PainelLogin.revalidate();
       
    }//GEN-LAST:event_BotaoLoginActionPerformed

    private void BotaoAcervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAcervoActionPerformed
              PainelRegistro.setVisible(false);
              PainelLogin.setVisible(false);
              PainelSolicitacoes.setVisible(false);
              PainelSugestoes.setVisible(false);
              PainelBusca.setVisible(true);            // Ativa somente o Painel de busca
           
    }//GEN-LAST:event_BotaoAcervoActionPerformed

    private void SearchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchBarKeyReleased
        String buscaText = SearchBar.getText();
        preencheTabelaLivros(buscaText);
    }//GEN-LAST:event_SearchBarKeyReleased

    private void SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBarActionPerformed

    private void BotaoSolicitacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSolicitacoesActionPerformed
 
            PainelSolicitacoes.setVisible(true);
            preencheTabelaSolicitacoes(usuarioLogado);
            PainelBusca.setVisible(false);
            PainelRegistro.setVisible(false);
            PainelLogin.setVisible(false);                         //Deixa apenas o painel de solicitçoes visivel
            PainelSugestoes.setVisible(false);
          
    }//GEN-LAST:event_BotaoSolicitacoesActionPerformed

    private void SolicitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SolicitarMouseClicked
    
       DefaultTableModel tabelaLivros = (DefaultTableModel)TabelaLivros.getModel();
        int linhaSelec = TabelaLivros.getSelectedRow();
        System.out.println(tabelaLivros.getValueAt(linhaSelec, 0));
        int idSelec = Integer.parseInt(tabelaLivros.getValueAt(linhaSelec, 0).toString());
        String resul = Solicitacoes.addSolicitacao(AdicionarUsuario.getIdUsuario(usuarioLogado.getNome()), idSelec);     
        
        if ("".equals(resul)){
            JOptionPane.showMessageDialog(this, "Você já possui o número máximo de solicitações", "Falha na solicitação!", JOptionPane.INFORMATION_MESSAGE);
        } else switch (resul) {
                case "1":
                    JOptionPane.showMessageDialog(this, "Não há exemplares deste livro ou estão indisponíveis no momento.", "Exemplar Indisponível", JOptionPane.INFORMATION_MESSAGE);
                    break;
                case "2":
                    JOptionPane.showMessageDialog(this, "Erro, o banco de dados da biblioteca pode estar fora do ar.", "Errol", JOptionPane.ERROR_MESSAGE);
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Solicitação adicionada com sucesso, você pode retirar o livro em até 2 horas no balcão da biblioteca.", "Solicitação Realizada!", JOptionPane.INFORMATION_MESSAGE);
                    break;
            }
    }//GEN-LAST:event_SolicitarMouseClicked

    private void SolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolicitarActionPerformed
        
        
    }//GEN-LAST:event_SolicitarActionPerformed

    private void BotaoSugerirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSugerirActionPerformed
              PainelRegistro.setVisible(false);
              PainelLogin.setVisible(false);
              PainelSolicitacoes.setVisible(false);
              PainelBusca.setVisible(false);   
              PainelSugestoes.setVisible(true);
    }//GEN-LAST:event_BotaoSugerirActionPerformed

    private void submeteSugestaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submeteSugestaoActionPerformed
      String autor = sugestaoAutor.getText().trim();
      String nome = sugestaoNome.getText().trim();
      int resul = Sugestao.adicionarSugestao(nome, autor);
        switch (resul) {
                case 3: 
                    JOptionPane.showMessageDialog(this, "Nós já possuimos esse livro, procure no acervo", "Livro já existe", JOptionPane.INFORMATION_MESSAGE);
                    break;
                case 2:
                    JOptionPane.showMessageDialog(this, "Erro de conexão.", "Conexão falhou", JOptionPane.ERROR_MESSAGE);
                    break;
                case 1:
                    JOptionPane.showMessageDialog(this, "Já existe uma sugestão para esse livro, iremos adquirilo o mais rápido possivel!", "Sugestão já existe", JOptionPane.INFORMATION_MESSAGE);
                    break;
                case 0:
                    JOptionPane.showMessageDialog(this, "Sugestão adicionada com sucesso", "Sugestão Recebida!", JOptionPane.INFORMATION_MESSAGE);
                    break;
            }
      
    }//GEN-LAST:event_submeteSugestaoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sugestaoVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sugestaoVolumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sugestaoVolumeActionPerformed

    private void AdicionarBibliotecarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarBibliotecarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdicionarBibliotecarioActionPerformed

    private void AdicionarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdicionarObraActionPerformed

    private void ExemplaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExemplaresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExemplaresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarBibliotecario;
    private javax.swing.JButton AdicionarObra;
    private javax.swing.JPanel BarraCima;
    private javax.swing.JButton BotaoAcervo;
    private javax.swing.JButton BotaoLogin;
    private javax.swing.JButton BotaoSolicitacoes;
    private javax.swing.JButton BotaoSugerir;
    private javax.swing.JButton Entrar;
    private javax.swing.JButton EnviarRegistro;
    private javax.swing.JButton Exemplares;
    private javax.swing.JPanel MenuBarAdmin;
    private javax.swing.JPanel MenuBarAluno;
    private javax.swing.JPanel PainelAddObra;
    private javax.swing.JPanel PainelBusca;
    private javax.swing.JPanel PainelLogin;
    private javax.swing.JPanel PainelRegistro;
    private javax.swing.JPanel PainelSolicitacoes;
    private javax.swing.JPanel PainelSugestoes;
    private javax.swing.JButton Registrar;
    private javax.swing.JScrollPane ScrollSoli;
    private java.awt.TextField SearchBar;
    private java.awt.Button Solicitar;
    private javax.swing.JTable TabelaLivros;
    private javax.swing.JTable TabelaSoli;
    private javax.swing.JLabel TextoBarraCima;
    private javax.swing.JTextField confSenhaBox;
    private javax.swing.JTextField emailBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeBox;
    private javax.swing.JTextField nomeLoginBox;
    private javax.swing.JTextField senhaBox;
    private javax.swing.JPasswordField senhaLoginBox;
    private javax.swing.JButton submeteSugestao;
    private javax.swing.JTextField sugestaoAutor;
    private javax.swing.JTextField sugestaoNome;
    private javax.swing.JTextField sugestaoVolume;
    // End of variables declaration//GEN-END:variables
}
